# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Copernicus Climate Change Service (C3S) training book
author: the Copernicus Climate Change Service (C3S), entrusted to ECMWF (European Centre for Medium-Range Weather Forecasts)

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "off"
  allow_errors: false

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/ecmwf-training/C3S-training # Online location of your book
  branch: main # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  announcement: "⚠️This is a TEST version, this is not an official website⚠️"
  extra_footer: |
    <script src="_static/custom.js"></script>

exclude_patterns: ["**.ipynb_checkpoints", "**README.md"]
    
launch_buttons:
  notebook_interface: "jupyterlab"  # or "classic"
  #  WAITING FOR JUPYTERHUB TO BE READY:
  # jupyterhub_url: "https://jupyterhub.ecmwf.int"
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
  #  COLAB AND DEEPNOTE NOT COMPATIBLE WITH SUBMODULES
  # colab_url: "https://colab.research.google.com"  # The URL for Google Colab (e.g., https://colab.research.google.com)
  # deepnote_url: "https://deepnote.com"  # The URL for Deepnote (e.g., https://deepnote.com)
