# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Copernicus Climate Change Service (C3S) Training Book
author: the Copernicus Climate Change Service (C3S), entrusted to ECMWF (European Centre for Medium-Range Weather Forecasts)

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "off"
  allow_errors: false

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/Randbee/C3SBook # Online location of your book
  branch: review # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  announcement: "⚠️This is a TEST Version, this is not an official website⚠️"

launch_buttons:
  binderhub_url: "https://mybinder.org" # The URL for your BinderHub (e.g., https://mybinder.org)

exclude_patterns: ["**.ipynb_checkpoints", "**README.md"]
