name: example-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - cdsapi
  - pandas
  - netCDF4
  - dask
  - xarray
  - matplotlib
  - cartopy
  - myst-parser
  - jupyterlab
