#!/usr/bin/env bash
branch=main
git reset --hard
git pull

here=${PWD}
for submodule in $(git submodule status | awk '{ print $2 }'); do
  git submodule update --init --recursive $submodule
  cd $submodule
  git checkout $branch
  git pull
  cd $here
done

git add .
git commit -m "Update submodules"
git push